const DATE_FORMAT = 'DD-MM-YYYY'

const YEAR_DATE_FORMAT = 'YYYY-MM-DD'

const DATE_FULL_FORMAT = 'DD-MMM-YYYY'

const TIME_FORMAT = 'HH:mm'

const TIME_FULL_FORMAT = 'HH:mm:ss'

const DATETIME_FORMAT = 'DD-MM-YYYY HH:mm'

const DATETIME_NOSEPARATOR_FORMAT = 'DDMMYYYYHHmmss'

const YEAR_DATETIME_FORMAT = 'YYYY-MM-DD HH:mm'

const DATETIME_FULL_FORMAT = 'DD-MM-YYYY HH:mm:ss'

const TIMEZONE_FORMAT = '(UTC Z)'

export {
    DATE_FORMAT,
    DATE_FULL_FORMAT,
    TIME_FORMAT,
    TIME_FULL_FORMAT,
    DATETIME_FORMAT,
    DATETIME_FULL_FORMAT,
    DATETIME_NOSEPARATOR_FORMAT,
    TIMEZONE_FORMAT,
    YEAR_DATE_FORMAT,
    YEAR_DATETIME_FORMAT
}
